steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
          '-t',
          'us-central1-docker.pkg.dev/loxol-376616/toolbox-repo/toolbox-image', 
          '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/loxol-376616/toolbox-repo/toolbox-image']

images:
- 'us-central1-docker.pkg.dev/loxol-376616/toolbox-repo/toolbox-image'
